require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # Make code changes take effect immediately without server restart.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
  # Run rails dev:cache to toggle Action Controller caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
  end

  # Change to :null_store to avoid any caching.
  config.cache_store = :memory_store

  # Store uploaded files on the local file system (see config/storage.yml for options).
  config.active_storage.service = :google

  smtp_setting = lambda do |env_key, credential_key, fallback = nil|
    ENV[env_key] || Rails.application.credentials.dig(:smtp, credential_key) || fallback
  end

  smtp_bool = lambda do |env_key, credential_key, fallback|
    ActiveModel::Type::Boolean.new.cast(smtp_setting.call(env_key, credential_key, fallback).to_s)
  end

  app_host = ENV["APP_HOST"] || Rails.application.credentials.dig(:app, :host) || "localhost"
  app_port = (ENV["APP_PORT"] || Rails.application.credentials.dig(:app, :port) || 3000).to_i
  app_protocol = ENV["APP_PROTOCOL"] || Rails.application.credentials.dig(:app, :protocol) || "http"
  smtp_port = smtp_setting.call("SMTP_PORT", :port, 587).to_i
  smtp_ssl = smtp_bool.call("SMTP_SSL", :ssl, false)
  smtp_starttls_requested = smtp_bool.call("SMTP_ENABLE_STARTTLS_AUTO", :enable_starttls_auto, !smtp_ssl && smtp_port != 465)
  smtp_starttls = (smtp_ssl || smtp_port == 465) ? false : smtp_starttls_requested
  smtp_from = smtp_setting.call("SMTP_FROM", :from, ENV.fetch("DEVISE_MAILER_SENDER", "no-reply@turfske.local"))

  # Make template changes take effect immediately.
  config.action_mailer.perform_caching = false
  config.action_mailer.default_url_options = { host: app_host, port: app_port, protocol: app_protocol }
  config.action_mailer.default_options = {
    from: smtp_from,
  }

  smtp_username = smtp_setting.call("SMTP_USERNAME", :user_name)
  smtp_password = smtp_setting.call("SMTP_PASSWORD", :password)

  if smtp_username.present? && smtp_password.present?
    config.action_mailer.delivery_method = :smtp
    config.action_mailer.perform_deliveries = true
    config.action_mailer.raise_delivery_errors = true
    config.action_mailer.smtp_settings = {
      address: smtp_setting.call("SMTP_ADDRESS", :address, "smtp.gmail.com"),
      port: smtp_port,
      domain: smtp_setting.call("SMTP_DOMAIN", :domain, app_host),
      user_name: smtp_username,
      password: smtp_password,
      authentication: smtp_setting.call("SMTP_AUTHENTICATION", :authentication, "plain").to_sym,
      enable_starttls_auto: smtp_starttls,
      ssl: smtp_ssl,
      openssl_verify_mode: smtp_setting.call("SMTP_OPENSSL_VERIFY_MODE", :openssl_verify_mode, "peer"),
    }
  else
    config.action_mailer.delivery_method = :test
    config.action_mailer.perform_deliveries = false
    config.action_mailer.raise_delivery_errors = false
  end
  
  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Append comments with runtime information tags to SQL queries in logs.
  config.active_record.query_log_tags_enabled = true

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Uncomment if you wish to allow Action Cable access from any origin.
  # config.action_cable.disable_request_forgery_protection = true

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!
end
